# Generated by Django 6.0 on 2026-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testemonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='momo',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='momo',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='momo',
            name='mark_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='momo',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
